### ISSUE TITLE
Not python3 compatible 

### ISSUE THREAD

**Issue by ndanielsen** [Adobe-Marketing-Cloud/python-pandas-lab#2]
It would be great if the omniture-python api worked with python 3.4+

**Comment by dancingcactus** [comment]
@ndanielsen I definitely agree. I have been working on a prototype with python 3 support. I am just trying to get the test coverage up before I merge it into master. 

You can download it here. 
`git clone -b python3_support https://github.com/dancingcactus/python-omniture.git`

then run 
`python3 setup.py install`

It works really well right now but don't hesitate to log bugs you find against it here. 
https://github.com/dancingcactus/python-omniture
